<?php

declare(strict_types=1);

return [
    'back' => 'Zurück zur Anmeldung',
    'updated' => 'Zuletzt aktualisiert: :date',
    'updated_date' => '6. Juli 2026',

    'terms' => [
        'title' => 'Nutzungsbedingungen',
        'sections' => [
            ['h' => '', 'p' => 'Diese Bedingungen regeln deinen Zugang zu und die Nutzung von Repunio (dem „Dienst“), einer Plattform zur Verwaltung von Google-Business-Profil-Bewertungen, Posts und verwandten Werkzeugen. Mit der Erstellung eines Kontos oder der Nutzung des Dienstes stimmst du diesen Bedingungen für dich selbst und jede von dir vertretene Organisation zu.'],
            ['h' => 'Das Konto', 'p' => 'Du bist für die Aktivitäten in deinem Workspace verantwortlich, für die sichere Aufbewahrung deiner Zugangsdaten und dafür, dass alle von dir eingeladenen Personen diese Bedingungen einhalten. Du musst zutreffende Angaben machen und berechtigt sein, die hinzugefügten Standorte zu verbinden.'],
            ['h' => 'Zulässige Nutzung', 'p' => 'Du verpflichtest dich, den Dienst nicht zu missbrauchen: keine rechtswidrigen Inhalte, keine Versuche, die Sicherheit zu umgehen oder auf fremde Daten zuzugreifen, kein automatisierter Missbrauch unserer API über die veröffentlichten Limits hinaus und keine Nutzung, die gegen die Richtlinien von Google Business Profil verstößt. Über Repunio veröffentlichte Antworten, Posts und Seiten sind deine eigenen Inhalte und in deiner Verantwortung.'],
            ['h' => 'Deine Inhalte', 'p' => 'Alle Rechte an den Inhalten, die du in den Dienst einbringst, bleiben bei dir: Bewertungsdaten, Antworten, Posts, Logos und Texte. Du räumst uns eine beschränkte Lizenz ein, diese Inhalte zu hosten, zu verarbeiten und anzuzeigen, ausschließlich um den Dienst für dich zu betreiben, einschließlich der Übermittlung von Bewertungstexten an unseren KI-Anbieter, wenn du KI-Funktionen nutzt. Du bestätigst, die nötigen Rechte an allem zu haben, was du hochlädst oder verbindest.'],
            ['h' => 'KI-Funktionen', 'p' => 'Teile des Dienstes erzeugen Inhalte mit künstlicher Intelligenz: Antwortentwürfe, Berichts-Zusammenfassungen, Chat-Antworten und Ähnliches. KI-Ausgaben können ungenau oder unvollständig sein. Prüfe KI-Inhalte vor der Veröffentlichung; wenn du die automatische Veröffentlichung aktivierst, übernimmst du die Verantwortung für das, was auf deinen Profilen erscheint. KI-Ausgaben sind keine Rechts-, Finanz- oder sonstige Fachberatung.'],
            ['h' => 'Dienste Dritter', 'p' => 'Der Dienst ist auf Dritte angewiesen, insbesondere Google Business Profil und unseren Verbindungs-Anbieter. Deren Verfügbarkeit, Datenqualität und Richtlinienänderungen liegen außerhalb unserer Kontrolle. Mit dem Verbinden eines Standorts ermächtigst du uns, dessen Business-Profil-Daten in deinem Auftrag abzurufen und zu verwalten. Für die Einhaltung der eigenen Bedingungen und Richtlinien von Google bleibst du selbst verantwortlich.'],
            ['h' => 'Abonnements und Abrechnung', 'p' => 'Bezahlte Tarife werden wiederkehrend im Voraus gemäß den beim Checkout angezeigten Preisen abgerechnet, pro verbundenem Standort. Du kannst jederzeit kündigen; der Zugang bleibt bis zum Ende der laufenden Abrechnungsperiode bestehen, und wir erstatten keine Teilperioden, sofern nicht gesetzlich vorgeschrieben. Preisänderungen kündigen wir mindestens 30 Tage im Voraus an.'],
            ['h' => 'Testphase, Kontingente und Credits', 'p' => 'Neue Workspaces können eine kostenlose Testphase mit vollem Funktionsumfang erhalten; danach ist ein bezahltes Abo nötig. Tarife enthalten monatliche KI-Kontingente, die mit jedem Abrechnungsmonat zurückgesetzt werden und nicht übertragbar sind. Gekaufte Zusatz-Credits verfallen nie, sind aber nicht erstattungsfähig und nicht übertragbar.'],
            ['h' => 'Sperrung und Beendigung', 'p' => 'Wir können den Zugang bei einem wesentlichen Verstoß gegen diese Bedingungen, bei Zahlungsverzug oder aus rechtlichen Gründen sperren oder beenden, nach Möglichkeit mit vorheriger Ankündigung. Du kannst deinen Workspace jederzeit in den Einstellungen löschen. Nach Löschung oder Beendigung gilt eine 30-tägige Frist, danach werden die Workspace-Daten endgültig entfernt, mit Ausnahme von Unterlagen, die wir aufbewahren müssen, etwa Rechnungen.'],
            ['h' => 'Verfügbarkeit und Änderungen', 'p' => 'Wir bemühen uns, den Dienst verfügbar zu halten, stellen ihn aber „wie besehen“ ohne Gewähr eines unterbrechungsfreien Betriebs bereit. Wir können Funktionen aktualisieren und werden wesentliche Änderungen dieser Bedingungen rechtzeitig ankündigen. Die weitere Nutzung nach einer Änderung gilt als Zustimmung.'],
            ['h' => 'Geistiges Eigentum', 'p' => 'Der Dienst, seine Software, sein Design und seine Marke bleiben unser Eigentum oder das unserer Lizenzgeber. Wenn du uns Feedback oder Vorschläge schickst, dürfen wir sie ohne Verpflichtung dir gegenüber nutzen.'],
            ['h' => 'Haftung', 'p' => 'Soweit gesetzlich zulässig, haftet Repunio nicht für indirekte oder Folgeschäden, und unsere Gesamthaftung ist auf die in den zwölf Monaten vor dem schadensauslösenden Ereignis gezahlten Gebühren begrenzt. Unberührt bleibt die Haftung, die gesetzlich nicht beschränkt werden kann, einschließlich für Vorsatz und grobe Fahrlässigkeit.'],
            ['h' => 'Freistellung', 'p' => 'Du stellst uns von Ansprüchen Dritter frei, die aus deinen Inhalten oder aus einer Nutzung des Dienstes unter Verstoß gegen diese Bedingungen entstehen, soweit du sie zu vertreten hast.'],
            ['h' => 'Datenschutz', 'p' => 'Wir verarbeiten personenbezogene Daten wie in der Datenschutzerklärung beschrieben. Für die von Google verbundenen Bewertungs- und Profildaten handeln wir als dein Auftragsverarbeiter und verarbeiten sie nur zur Bereitstellung des Dienstes; ein Auftragsverarbeitungsvertrag ist auf Anfrage erhältlich.'],
            ['h' => 'Anwendbares Recht', 'p' => 'Diese Bedingungen unterliegen österreichischem Recht unter Ausschluss der Kollisionsnormen. Ausschließlicher Gerichtsstand ist Wien, Österreich. Zwingende Verbraucherschutzrechte deines Wohnsitzlandes bleiben unberührt.'],
            ['h' => 'Schlussbestimmungen', 'p' => 'Sollte eine Bestimmung dieser Bedingungen unwirksam sein, bleibt der Rest wirksam. Diese Bedingungen, die Bestelldaten beim Checkout und die hier verlinkten Richtlinien bilden die gesamte Vereinbarung zwischen dir und uns über den Dienst.'],
            ['h' => 'Kontakt', 'p' => 'Fragen zu diesen Bedingungen kannst du an legal@repunio.com senden.'],
        ],
    ],

    'privacy' => [
        'title' => 'Datenschutzerklärung',
        'sections' => [
            ['h' => '', 'p' => 'Diese Erklärung beschreibt, welche personenbezogenen Daten Repunio verarbeitet, zu welchem Zweck und welche Wahlmöglichkeiten du hast. Repunio wird aus Österreich betrieben. Für deine Kontodaten sind wir Verantwortlicher, für die von Google verbundenen Bewertungs- und Profildaten Auftragsverarbeiter.'],
            ['h' => 'Was wir erheben', 'p' => 'Kontodaten (Name, E-Mail, Passwort-Hash, Sprache, Avatar), Workspace- und Abrechnungsinformationen (Tarif, Rechnungen; Kartennummern verarbeitet Stripe, sie erreichen unsere Server nie), die von dir verbundenen Standorte, Bewertungen und Antworten von Google, im Dienst erstellte Inhalte (Posts, Bewertungsseiten, Berichts-Einstellungen, KI-Anweisungen), Wettbewerber-Einträge, die du beobachtest (öffentliche Google-Daten), sowie technische Daten wie Protokolle und Nutzungsdaten, die zum Betrieb und zur Absicherung des Dienstes nötig sind.'],
            ['h' => 'Wie wir sie nutzen', 'p' => 'Zur Bereitstellung des Dienstes, zur Erstellung von Berichten und Auswertungen, zum Versand von Transaktions- und (falls aktiviert) Benachrichtigungs- und Onboarding-E-Mails, zur Zahlungsabwicklung, zur Missbrauchsprävention und zur Erfüllung gesetzlicher Pflichten. Wenn du KI-Funktionen nutzt, werden Bewertungstexte und deine Anweisungen an unseren KI-Anbieter übermittelt, um die gewünschte Ausgabe zu erzeugen; wir verwenden deine Daten nicht zum Training von KI-Modellen. Wir verkaufen deine personenbezogenen Daten nicht.'],
            ['h' => 'Rechtsgrundlagen', 'p' => 'Wir verarbeiten Daten zur Vertragserfüllung (Betrieb des Dienstes), aufgrund berechtigter Interessen (Absicherung und Verbesserung des Dienstes, Missbrauchsprävention), mit deiner Einwilligung, wo erforderlich (optionale E-Mail-Serien, Chat-Kanal-Integrationen), und zur Erfüllung rechtlicher Pflichten (Steuer- und Buchhaltungsunterlagen).'],
            ['h' => 'Eingesetzte Auftragsverarbeiter', 'p' => 'Wir geben Daten nur an Auftragsverarbeiter weiter, die uns beim Betrieb helfen: Stripe (Zahlungen), Postmark (E-Mail-Versand), Zernio (Google-Business-Profil-Anbindung und Bewertungsdaten), Anthropic (KI-Texterzeugung), Google (Anmeldung, Business Profil, Places-Daten für Wettbewerber), Slack und Telegram nur, wenn du sie verbindest, sowie unser Hosting-Anbieter. Jeder ist vertraglich verpflichtet, deine Daten zu schützen und nur nach unseren Weisungen zu verarbeiten.'],
            ['h' => 'Internationale Übermittlungen', 'p' => 'Einige Auftragsverarbeiter sitzen außerhalb der EU/des EWR, insbesondere in den USA. In diesen Fällen sind die Übermittlungen durch EU-Standardvertragsklauseln oder einen Angemessenheitsbeschluss wie das EU-US Data Privacy Framework abgesichert.'],
            ['h' => 'Aufbewahrung', 'p' => 'Wir speichern Daten, solange dein Konto aktiv ist. Löschst du einen Workspace, bleiben seine Daten für eine 30-tägige Frist erhalten (damit eine versehentliche Löschung rückgängig gemacht werden kann) und werden dann endgültig entfernt. Rechnungen und ähnliche Unterlagen bewahren wir für die gesetzliche Dauer auf. Backups werden zyklisch bereinigt.'],
            ['h' => 'Deine Rechte', 'p' => 'Nach der DSGVO kannst du Auskunft über deine personenbezogenen Daten, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit verlangen, der Verarbeitung aufgrund berechtigter Interessen widersprechen und Einwilligungen jederzeit widerrufen. Du kannst dich außerdem bei einer Aufsichtsbehörde beschweren, in Österreich bei der Datenschutzbehörde (dsb.gv.at).'],
            ['h' => 'Sicherheit', 'p' => 'Daten werden bei der Übertragung verschlüsselt, der Zugriff ist rollenbasiert beschränkt, jeder Workspace liegt in einer eigenen, isolierten Datenbank, und Zwei-Faktor-Authentifizierung steht allen Konten zur Verfügung.'],
            ['h' => 'Automatisierte Entscheidungen', 'p' => 'KI-Funktionen entwerfen Inhalte und Zusammenfassungen für dich. Wir treffen keine automatisierten Entscheidungen mit rechtlicher oder ähnlich erheblicher Wirkung über dich.'],
            ['h' => 'Kinder', 'p' => 'Der Dienst richtet sich an Unternehmen und nicht an Kinder unter 16 Jahren. Wir erheben deren Daten nicht wissentlich.'],
            ['h' => 'Änderungen', 'p' => 'Wir können diese Erklärung aktualisieren. Wesentliche Änderungen kündigen wir im Dienst oder per E-Mail an, bevor sie wirksam werden.'],
            ['h' => 'Kontakt', 'p' => 'Für Datenschutzanfragen wende dich an privacy@repunio.com.'],
        ],
    ],

    'cookies' => [
        'title' => 'Cookie-Richtlinie',
        'sections' => [
            ['h' => '', 'p' => 'Diese Richtlinie erklärt, wie Repunio Cookies und ähnliche Technologien bei der Nutzung des Dienstes einsetzt.'],
            ['h' => 'Notwendige Cookies', 'p' => 'Wir verwenden unbedingt erforderliche Cookies, um dich angemeldet zu halten, deine Sprachwahl zu merken, vor Request-Forgery zu schützen und deine Sitzung aufrechtzuerhalten. Ohne sie funktioniert der Dienst nicht, daher sind sie nicht optional.'],
            ['h' => 'Cookies, die wir setzen', 'p' => 'Das Sitzungs-Cookie (meldet dich an und läuft mit dem Ende der Sitzung ab), das Sicherheits-Token-Cookie (schützt Formulare vor Request-Forgery), ein optionales „Angemeldet bleiben“-Cookie, wenn du das Häkchen bei der Anmeldung setzt, und ein Präferenz-Cookie für deine Sprache.'],
            ['h' => 'Präferenzen', 'p' => 'Einige Cookies merken sich Einstellungen wie deine gewählte Sprache oder deinen Workspace, damit du sie nicht bei jedem Besuch erneut auswählen musst.'],
            ['h' => 'Was wir nicht tun', 'p' => 'Wir verwenden keine Werbe-Cookies, kein Tracking durch Dritte und verkaufen keine über Cookies erhobenen Daten. Etwaige Analysen beschränken sich darauf, den Dienst zu verstehen und zu verbessern.'],
            ['h' => 'Cookies verwalten', 'p' => 'Du kannst Cookies in deinen Browser-Einstellungen löschen oder blockieren; das Deaktivieren notwendiger Cookies verhindert jedoch die Anmeldung und Nutzung des Dienstes.'],
            ['h' => 'Kontakt', 'p' => 'Fragen zu Cookies kannst du an privacy@repunio.com senden.'],
        ],
    ],
];
